project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "CPLN6800 GIS Capstone"
  site-url: "https://cyanhang.github.io/CPLN6800/" 
  repo-url: https://github.com/Cyanhang/CPLN6800 
  repo-actions: [source]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-Ke Zhou, Hang Zhao, Timothy Oliver, Nohman; 2024"

  sidebar:
    logo: "images/UPenn.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://ceclab.seas.upenn.edu/
        text: "Clean Energy Conversion Lab, Kleinman Center for Energy Policy"
      - icon: github
        href: https://github.com/Cyanhang/CPLN6800
        text: "GitHub"
      

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Main
      - about.qmd
      - section: Exploratory Analysis/index.qmd
        contents:
          - Exploratory Analysis/1-python-code-blocks.qmd 
          - Exploratory Analysis/2-static-images.ipynb
          - Exploratory Analysis/3-altair-hvplot.ipynb
          - Exploratory Analysis/4-folium.ipynb
      - section: Preliminary Results/index.qmd
        contents:
          - Preliminary Results/1-python-code-blocks.qmd 

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




